# Generated by Django 3.0.3 on 2020-05-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('desc', models.CharField(blank=True, max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('file_path', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'list_1',
            },
        ),
        migrations.CreateModel(
            name='List_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('desc', models.CharField(blank=True, max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('file_path', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.List_1')),
            ],
            options={
                'db_table': 'list_2',
            },
        ),
    ]
