# Generated by Django 3.0.3 on 2020-05-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('image', models.CharField(blank=True, max_length=50)),
                ('url_1', models.CharField(blank=True, max_length=255)),
                ('url_2', models.CharField(blank=True, max_length=255)),
                ('years', models.IntegerField(blank=True)),
                ('director', models.CharField(blank=True, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('actor', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=20)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.List_2')),
            ],
            options={
                'db_table': 'movies_content',
            },
        ),
    ]
