# Generated by Django 3.0.3 on 2020-05-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='desc',
            field=models.TextField(blank=True, max_length=388),
        ),
    ]
