# Generated by Django 3.0.3 on 2020-05-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200510_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(blank=True, max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movies',
            name='url_1',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
