# Generated by Django 3.0.3 on 2020-05-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200510_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='file_path',
            new_name='statics_files',
        ),
        migrations.AlterField(
            model_name='list_1',
            name='desc',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='list_1',
            name='url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='list_2',
            name='desc',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='list_2',
            name='url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='url_2',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
