# Generated by Django 3.0.3 on 2020-05-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20200510_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
